name: Testing workflow for Golang

on:
  push:
    paths:
      - '**.go'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: lint
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go install golang.org/x/lint/golint
        golint ./...

    - name: vet
      run: go vet ./...

    - name: test
      run: go test ./...

    - name: Slack Notification Failure
      if: failure()
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: '#dc143c'
        SLACK_TITLE: 'Failed CI for Golang :boom:'
        SLACK_MESSAGE: ':closed_book: ${{ github.repository }}'
